-- Load sample data into the e-commerce database
-- This data is based on common e-commerce patterns

-- Insert Products
INSERT INTO products (product_name, description, category, price, stock_quantity) VALUES
('Laptop Pro 15"', 'High-performance laptop with 16GB RAM and 512GB SSD', 'Electronics', 1299.99, 50),
('Wireless Mouse', 'Ergonomic wireless mouse with long battery life', 'Electronics', 29.99, 200),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard with blue switches', 'Electronics', 89.99, 150),
('Monitor 27" 4K', '27-inch 4K UHD monitor with HDR support', 'Electronics', 399.99, 75),
('USB-C Hub', '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader', 'Electronics', 49.99, 300),
('Coffee Maker Deluxe', 'Programmable coffee maker with thermal carafe', 'Home & Kitchen', 89.99, 100),
('Air Fryer XL', '5.8QT capacity air fryer with digital display', 'Home & Kitchen', 129.99, 80),
('Stand Mixer', '5-quart stand mixer with multiple attachments', 'Home & Kitchen', 299.99, 60),
('Yoga Mat Premium', 'Non-slip yoga mat with carrying strap', 'Sports & Outdoors', 39.99, 200),
('Running Shoes', 'Lightweight running shoes with cushioned sole', 'Sports & Outdoors', 119.99, 150),
('Backpack Travel', '40L travel backpack with USB charging port', 'Sports & Outdoors', 79.99, 120),
('Water Bottle Insulated', '32oz stainless steel insulated water bottle', 'Sports & Outdoors', 34.99, 250),
('Leather Wallet', 'Genuine leather bifold wallet with RFID blocking', 'Accessories', 49.99, 180),
('Sunglasses Classic', 'UV protection sunglasses with polarized lenses', 'Accessories', 79.99, 140),
('Smart Watch', 'Fitness tracker with heart rate monitor and GPS', 'Electronics', 199.99, 90),
('Bluetooth Headphones', 'Noise-cancelling wireless headphones', 'Electronics', 179.99, 110),
('Desk Lamp LED', 'Adjustable LED desk lamp with USB port', 'Home & Kitchen', 44.99, 160),
('Throw Pillow Set', 'Set of 4 decorative throw pillows', 'Home & Kitchen', 39.99, 200),
('Puzzle 1000 Pieces', 'Jigsaw puzzle with beautiful landscape image', 'Toys & Games', 19.99, 300),
('Board Game Strategy', 'Popular strategy board game for 2-4 players', 'Toys & Games', 49.99, 100);

-- Insert Customers
INSERT INTO customers (first_name, last_name, email, phone, address, city, state, country, zip_code) VALUES
('John', 'Smith', 'john.smith@email.com', '555-0101', '123 Main St', 'New York', 'NY', 'USA', '10001'),
('Sarah', 'Johnson', 'sarah.j@email.com', '555-0102', '456 Oak Ave', 'Los Angeles', 'CA', 'USA', '90001'),
('Michael', 'Brown', 'michael.brown@email.com', '555-0103', '789 Pine Rd', 'Chicago', 'IL', 'USA', '60601'),
('Emily', 'Davis', 'emily.davis@email.com', '555-0104', '321 Elm St', 'Houston', 'TX', 'USA', '77001'),
('David', 'Wilson', 'david.w@email.com', '555-0105', '654 Maple Dr', 'Phoenix', 'AZ', 'USA', '85001'),
('Jessica', 'Martinez', 'jessica.m@email.com', '555-0106', '987 Cedar Ln', 'Philadelphia', 'PA', 'USA', '19101'),
('Robert', 'Anderson', 'robert.a@email.com', '555-0107', '147 Birch Way', 'San Antonio', 'TX', 'USA', '78201'),
('Amanda', 'Taylor', 'amanda.t@email.com', '555-0108', '258 Spruce St', 'San Diego', 'CA', 'USA', '92101'),
('James', 'Thomas', 'james.t@email.com', '555-0109', '369 Willow Ave', 'Dallas', 'TX', 'USA', '75201'),
('Lisa', 'Jackson', 'lisa.j@email.com', '555-0110', '741 Cherry Blvd', 'San Jose', 'CA', 'USA', '95101'),
('William', 'White', 'william.w@email.com', '555-0111', '852 Peach St', 'Austin', 'TX', 'USA', '78701'),
('Ashley', 'Harris', 'ashley.h@email.com', '555-0112', '963 Apple Rd', 'Jacksonville', 'FL', 'USA', '32201'),
('Christopher', 'Martin', 'chris.m@email.com', '555-0113', '159 Orange Ave', 'Fort Worth', 'TX', 'USA', '76101'),
('Michelle', 'Thompson', 'michelle.t@email.com', '555-0114', '357 Grape St', 'Columbus', 'OH', 'USA', '43201'),
('Daniel', 'Garcia', 'daniel.g@email.com', '555-0115', '753 Lemon Dr', 'Charlotte', 'NC', 'USA', '28201'),
('Jennifer', 'Martinez', 'jennifer.m@email.com', '555-0116', '951 Banana Ln', 'San Francisco', 'CA', 'USA', '94101'),
('Matthew', 'Robinson', 'matt.r@email.com', '555-0117', '147 Strawberry Way', 'Indianapolis', 'IN', 'USA', '46201'),
('Nicole', 'Clark', 'nicole.c@email.com', '555-0118', '258 Blueberry St', 'Seattle', 'WA', 'USA', '98101'),
('Andrew', 'Rodriguez', 'andrew.r@email.com', '555-0119', '369 Raspberry Ave', 'Denver', 'CO', 'USA', '80201'),
('Stephanie', 'Lewis', 'stephanie.l@email.com', '555-0120', '741 Blackberry Blvd', 'Washington', 'DC', 'USA', '20001');

-- Insert Orders
INSERT INTO orders (customer_id, order_date, status, shipping_address, notes) VALUES
((SELECT customer_id FROM customers WHERE email = 'john.smith@email.com'), '2024-01-15 10:30:00', 'delivered', '123 Main St, New York, NY 10001', 'Please leave at front door'),
((SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com'), '2024-01-16 14:20:00', 'shipped', '456 Oak Ave, Los Angeles, CA 90001', NULL),
((SELECT customer_id FROM customers WHERE email = 'michael.brown@email.com'), '2024-01-17 09:15:00', 'processing', '789 Pine Rd, Chicago, IL 60601', 'Gift wrapping requested'),
((SELECT customer_id FROM customers WHERE email = 'emily.davis@email.com'), '2024-01-18 11:45:00', 'delivered', '321 Elm St, Houston, TX 77001', NULL),
((SELECT customer_id FROM customers WHERE email = 'david.w@email.com'), '2024-01-19 16:00:00', 'shipped', '654 Maple Dr, Phoenix, AZ 85001', NULL),
((SELECT customer_id FROM customers WHERE email = 'jessica.m@email.com'), '2024-01-20 13:30:00', 'pending', '987 Cedar Ln, Philadelphia, PA 19101', NULL),
((SELECT customer_id FROM customers WHERE email = 'john.smith@email.com'), '2024-01-21 10:00:00', 'delivered', '123 Main St, New York, NY 10001', NULL),
((SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com'), '2024-01-22 15:20:00', 'processing', '456 Oak Ave, Los Angeles, CA 90001', NULL),
((SELECT customer_id FROM customers WHERE email = 'robert.a@email.com'), '2024-01-23 09:00:00', 'shipped', '147 Birch Way, San Antonio, TX 78201', NULL),
((SELECT customer_id FROM customers WHERE email = 'amanda.t@email.com'), '2024-01-24 12:30:00', 'delivered', '258 Spruce St, San Diego, CA 92101', NULL),
((SELECT customer_id FROM customers WHERE email = 'james.t@email.com'), '2024-01-25 14:45:00', 'processing', '369 Willow Ave, Dallas, TX 75201', NULL),
((SELECT customer_id FROM customers WHERE email = 'lisa.j@email.com'), '2024-01-26 11:15:00', 'pending', '741 Cherry Blvd, San Jose, CA 95101', NULL),
((SELECT customer_id FROM customers WHERE email = 'william.w@email.com'), '2024-01-27 16:30:00', 'delivered', '852 Peach St, Austin, TX 78701', NULL),
((SELECT customer_id FROM customers WHERE email = 'ashley.h@email.com'), '2024-01-28 10:00:00', 'shipped', '963 Apple Rd, Jacksonville, FL 32201', NULL),
((SELECT customer_id FROM customers WHERE email = 'chris.m@email.com'), '2024-01-29 13:20:00', 'delivered', '159 Orange Ave, Fort Worth, TX 76101', NULL);

-- Insert Order Items
INSERT INTO order_items (order_id, product_id, quantity, unit_price, subtotal) VALUES
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Laptop Pro 15"'), 1, 1299.99, 1299.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Wireless Mouse'), 1, 29.99, 29.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Monitor 27" 4K'), 1, 399.99, 399.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'michael.brown@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Mechanical Keyboard'), 1, 89.99, 89.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'michael.brown@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'USB-C Hub'), 1, 49.99, 49.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'emily.davis@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Coffee Maker Deluxe'), 1, 89.99, 89.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'david.w@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Air Fryer XL'), 1, 129.99, 129.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'jessica.m@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Yoga Mat Premium'), 1, 39.99, 39.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'jessica.m@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Running Shoes'), 1, 119.99, 119.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com') ORDER BY order_date DESC LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Bluetooth Headphones'), 1, 179.99, 179.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com') ORDER BY order_date DESC LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Smart Watch'), 1, 199.99, 199.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'robert.a@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Stand Mixer'), 1, 299.99, 299.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'amanda.t@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Backpack Travel'), 1, 79.99, 79.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'amanda.t@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Water Bottle Insulated'), 2, 34.99, 69.98),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'james.t@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Leather Wallet'), 1, 49.99, 49.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'james.t@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Sunglasses Classic'), 1, 79.99, 79.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'lisa.j@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Desk Lamp LED'), 1, 44.99, 44.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'william.w@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Throw Pillow Set'), 1, 39.99, 39.99),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'ashley.h@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Puzzle 1000 Pieces'), 2, 19.99, 39.98),
((SELECT order_id FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE email = 'chris.m@email.com') LIMIT 1),
 (SELECT product_id FROM products WHERE product_name = 'Board Game Strategy'), 1, 49.99, 49.99);

-- Insert Reviews
INSERT INTO reviews (product_id, customer_id, rating, review_text) VALUES
((SELECT product_id FROM products WHERE product_name = 'Laptop Pro 15"'),
 (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com'), 5, 'Excellent laptop! Fast performance and great build quality.'),
((SELECT product_id FROM products WHERE product_name = 'Wireless Mouse'),
 (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com'), 4, 'Comfortable and responsive. Battery lasts a long time.'),
((SELECT product_id FROM products WHERE product_name = 'Monitor 27" 4K'),
 (SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com'), 5, 'Amazing picture quality! Colors are vibrant and crisp.'),
((SELECT product_id FROM products WHERE product_name = 'Coffee Maker Deluxe'),
 (SELECT customer_id FROM customers WHERE email = 'emily.davis@email.com'), 4, 'Makes great coffee and keeps it hot for hours.'),
((SELECT product_id FROM products WHERE product_name = 'Air Fryer XL'),
 (SELECT customer_id FROM customers WHERE email = 'david.w@email.com'), 5, 'Love this air fryer! Makes cooking so much easier and healthier.'),
((SELECT product_id FROM products WHERE product_name = 'Running Shoes'),
 (SELECT customer_id FROM customers WHERE email = 'jessica.m@email.com'), 5, 'Very comfortable for long runs. Great support and cushioning.'),
((SELECT product_id FROM products WHERE product_name = 'Bluetooth Headphones'),
 (SELECT customer_id FROM customers WHERE email = 'john.smith@email.com'), 5, 'Best headphones I have ever owned. Noise cancellation is incredible.'),
((SELECT product_id FROM products WHERE product_name = 'Smart Watch'),
 (SELECT customer_id FROM customers WHERE email = 'sarah.j@email.com'), 4, 'Good fitness tracker. Battery could be better but overall satisfied.'),
((SELECT product_id FROM products WHERE product_name = 'Stand Mixer'),
 (SELECT customer_id FROM customers WHERE email = 'robert.a@email.com'), 5, 'Perfect for baking! Powerful and easy to use.'),
((SELECT product_id FROM products WHERE product_name = 'Water Bottle Insulated'),
 (SELECT customer_id FROM customers WHERE email = 'amanda.t@email.com'), 5, 'Keeps drinks cold all day. Very durable and well-designed.');

